---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-deployment
  labels:
    app: vllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm
  template:
    metadata:
      labels:
        app: vllm
    spec:
      containers:
        - name: vllm-container
          image: vllm/vllm-openai:v0.5.0.post1
          imagePullPolicy: Always
          env:
            - name: VERBOSE
              value: "1"
          ports:
            - name: api
              containerPort: 8000
          resources:
            limits:
              cpu: "16"
              memory: 100G
              nvidia.com/gpu: "4"
          args: [
            "--model",
            "meta-llama/Meta-Llama-3-70B-Instruct",
            "--tensor-parallel-size",
            "4",
          ]
          volumeMounts:
            - name: shm
              mountPath: /dev/shm
      volumes:
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 12Gi

---
apiVersion: v1
kind: Service
metadata:
  name: vllm-service
  labels:
    app: vllm
spec:
  type: ClusterIP
  selector:
    app: vllm
  ports:
    - name: http
      port: 80
      targetPort: 8000
              